---
title: "Lecturas"
---

Todas las lecturas de capítulos de libro son obligatorias pues permiten una discusión informada en la clase. Las lecturas marcadas con “*” no serán cubiertas en clase, pero son ampliamente recomendables. En las sesiones de exposiciones cada alumno presentará uno de los artículos enlistados con negritas, por lo que se espera que el resto de la clase tenga el conocimiento suficiente para participar en la discusión.


## Prerrequisitos
* Modelos lineales
  +  W, Capítulos 1-4

## Semana 1

* Introducción
  + Angrist, J. D., & Pischke, J. S. (2017). Undergraduate Econometrics Instruction: Through Our Classes, Darkly. *Journal of Economic Perspectives*,31(2), 125-44.
  + \* Nakamura, E., & Steinsson, J. (2018). Identification in macroeconomics. _Journal of Economic Perspectives_, 32(3), 59-86.
  
* MCO
  + CT, Capítulo 4 (secciones 4.1 a 4.3)

## Semana 2

* Teoría asintótica
  + CT, Capítulo 4, (sección 4.4)

* Estimadores extremos
  + CT, Capítulo 5

## Semana 3

* Prueba de hipótesis
  + CT, Capítulo 7

## Semana 4
* Variable dependiente binaria
  + CT, Capítulo 14 (secciones 14.1 - 14.4)
  + **Binaria**: Avila-Foucat, V. S., & Pérez-Campuzano, E. (2015). Municipality socioeconomic characteristics and the probability of occurrence of Wildlife Management Units in Mexico. *Environmental Science & Policy*, 45, 146-153.
  + \* **Ordenados**: Conigliani, C., Manca, A., & Tancredi, A. (2015). Prediction of patient-reported outcome measures via multivariate ordered probit models. *Journal of the Royal Statistical Society*. Series A (Statistics in Society), 567-591.

* Variable dependiente categórica
  + CT, Capítulo 15 (secciones 15.1 - 15.4)
  + **Multinomial**: Kveder, C. L. M., & Flahaux, M. L. (2013). Returning to Dakar: A mixed methods analysis of the role of migration experience for occupational status. *World Development*, 45, 223-238.


## Semana 5


* Modelos de conteo

  + CT, Capítulo 20 (secciones 20.1 - 20.4).
  + \* **Poisson**: White, K., & Buckley, C. J. (2011). Exposure to international migration and its effect on childbearing in Turkey. International *Migration Review*, 45(1), 123-147.
  + \* **Negativo binomial**: Antón, J. I., & De Bustillo, R. M. (2010). Health care utilisation and immigration in Spain. *The European Journal of Health Economics*, 11(5), 487-498.
  + \* **Inflado en cero**: Young, J. D., Anderson, N. M., Naughton, H. T., & Mullan, K. (2018). Economic and policy factors driving adoption of institutional woody biomass heating systems in the US. *Energy Economics*, 69, 456-470.
  + \* **Dos partes**: Colchero, M. A., Molina, M., & Guerrero-López, C. M. (2017). After Mexico implemented a tax, purchases of sugar-sweetened beverages decreased and water increased: difference by place of residence, household composition, and income level. *The Journal of nutrition*, 147(8), 1552-1557.



## Semana 6

* Modelos de selección
  + CT, Capítulo 16 (secciones 16.1 – 16.6)
  + **Tobit**: Zou, B., & Luo, B. (2019). Rural Household Energy Consumption Characteristics and Determinants in China. Energy.
  + \* **Heckman**: Parey, M., Ruhose, J., Waldinger, F., & Netz, N. (2017). The selection of high-skilled emigrants. *Review of Economics and Statistics*, 99(5), 776-792.
  + \* **Ordenado + selección**: Alemi, F., Circella, G., Mokhtarian, P., & Handy, S. (2019). What drives the use of ridehailing in California? Ordered probit models of the usage frequency of Uber and Lyft. *Transportation Research Part C: Emerging Technologies*, 102, 233-248.


## Semana 7

* Variables instrumentales
  + W, Capítulo 5.
  + CT, Capítulo 4 (secciones 4.8 y 4.9)

## Semana 8

* Método generalizado de momentos
  + CT, Capítulo 6 (secciones 6.1 - 6.4)

## Semana 9

* Variables instrumentales en la práctica
  + **VI**: Hackett, L., & Marquez-Padilla, F. (2019). Working for Change: the Effect of Female Labor Force Participation on Fertility. SSRN Working Paper 3354753.
  + **VI**: López-Feldman, A., & Chávez, E. (2017). Remittances and natural resource extraction: Evidence from Mexico. *Ecological Economics*, 132, 69-79.

* Otras aplicaciones de VI
  + \* **VI**: Campos-Vazquez, R. M., & Nuñez, R. (2019). Obesity and labor market outcomes in Mexico/Obesidad y el mercado de trabajo en México. *Estudios Económicos*, 34(2), 159-196.
  + \* **MC2E2M**: Mocetti, S. (2007). Intergenerational earnings mobility in Italy. *The BE Journal of Economic Analysis & Policy*, 7(2).  
  + \* **Poisson + VI**: Hirvonen, K., & Hoddinott, J. (2017). Agricultural production and children's diets: Evidence from rural Ethiopia. *Agricultural Economics*, 48(4), 469-480.


## Semana 10

* Modelos y estimadores de panel
  + CT, Capítulo 21
  + **Panel**: Amare, M., Abay, K. A., Tiberti, L., & Chamberlin, J. (2021). COVID-19 and food security: Panel data evidence from Nigeria. *Food policy*, 101, 102099.
  + **Panel**: Kagin, J., Taylor, J. E., & Yúnez-Naude, A. (2016). Inverse productivity or inverse efficiency? Evidence from Mexico. *The Journal of Development Studies*, 52(3), 396-411.
  + \* **Panel**: Bwalya, S. M. (2006). Foreign direct investment and technology spillovers: Evidence from panel data analysis of manufacturing firms in Zambia. *Journal of development economics*, 81(2), 514-526.
  + \* **Panel + DID**: Estrada, R. (2019). Rules versus discretion in public service: Teacher hiring in Mexico. *Journal of Labor Economics*, 37(2), 545-579.

## Semana 11

* Temas de errores estándar
  + MHE, Capítulo 8

## Semana 12

* Bootstrap
  + CT, Capítulo 11
  + **Bootstrap**: Li, H., & Maddala, G. S. (1999). Bootstrap variance estimation of nonlinear functions of parameters: an application to long-run elasticities of energy demand. *Review of Economics and Statistics*, 81(4), 728-733.

* Regresión cuantil
  + CT, Capítulo 4 (sección 4.6)
  + **Cuantil**: Engelhardt, G. V., & Kumar, A. (2011). Pensions and household wealth accumulation. *Journal of Human Resources*, 46(1), 203-236.

## Semana 13

* Métodos semiparamétricos
  + CT, Capítulo 9
  + **Semiparamétrico**: Hussinger, K. (2008). R&D and subsidies at the firm level: An application of parametric and semiparametric two‐step selection models. *Journal of applied econometrics*, 23(6), 729-747.


## Extensiones

* Panel no lineal
  + CT, Capítulo 23
  + \* **Panel Poisson**: Castillo, J. C., Mejía, D., & Restrepo, P. (2020). Scarcity without leviathan: The violent effects of cocaine supply shortages in the mexican drug war. *Review of Economics and Statistics*, 102(2), 269-286.

* Panel con endogeneidad
  + CT, Capítulo 22 (secciones 22.1 - 22.5)
  + \* **Panel + VI**: Antman, F. M. (2011). The intergenerational effects of paternal migration on schooling and work: What can we learn from children's time allocations?. *Journal of Development Economics*, 96(2), 200-208.
  + \* Wooldridge, J. (2012). Panel data models with heterogeneity and endogeneity. Institute for Fiscal Studies.
  + \* Semykina, A., & Wooldridge, J. M. (2010). Estimating panel data models in the presence of endogeneity and selection. _Journal of Econometrics_, 157(2), 375-380.

* Modelos de riesgo y sobrevivencia
  + CT, Capítulo 17 (secciones 17.1 – 17.4 y 17.6-17.11)
  + \* **Riesgo**: De Uña-Alvarez, J., Otero-Giráldez, M. S., & Alvarez-Llorente, G. (2003). Estimation under length-bias and right-censoring: an application to unemployment duration analysis for married women. *Journal of Applied Statistics*, 30(3), 283-291.



