---
title: "Presentaciones"
---


Por favor, seleccione una de las lecturas marcadas con una "+" de la lista de lecturas y envíe un correo al profesor para que se le asigne una fecha de presentación.


|     |                Morning              |          Afternoon                     |
|:---:|:-----------------------------------:|:--------------------------------------:|
|  L  | Intro + Data manipulation           | git / GitHub                           |
|  M  | Generalised Linear Models           | Data visualisation                     |
|  X  | Mixed models / GAM / Bayes          | Functional programming + Students work |
|  J  | Multivariate analyses               | Reproducible workflows                 |
|  V  | Using R as GIS + Students work      | Project presentations                  |



| **Autores** | **Tema** | **Presentador o presentadora** | **Fecha de exposición** |
| --- | --- | --- | --- |
| Avila-Foucat et al. (2015) | Binaria  | | 4 de octubre |  
| Zou & Luo (2019) | Tobit |   | 4 de octubre |
| López-Feldman & Chávez (2017) | VI |  | 18 de octubre |
 Hackett & Márquez (2019) | VI |  | 18  de octubre|
| Bwalya (2006) | Panel |  | 3 de noviembre |
| Kagin et al. (2016) | Panel |  | 3 de noviembre |
| Engelhardt & Kumar (2011) | Cuantil |  |  24 de noviembre |
| Hussinger (2008)| Semiparamétrico |  | 24 de noviembre |

