---
title: "Proyecto 2"
lang: es
---

## Instrucciones

Fecha de entrega: **viernes 3 de octubre a las 20:00 en Teams**

El proyecto deberá entregarse en Teams. Deberá incluir dos documentos:

Un primer documento de respuestas donde se reporten las conclusiones del análisis y debe ser generado usando un software de procesamiento de textos científicos, por ejemplo, usando los lenguajes LaTeX o Markdown.

Un segundo archivo deberá contener el código replicable usado para generar los resultados de la sección práctica. El código debe también crear las tablas y gráficas solicitadas. Los archivos de código se verificarán para comprobar su replicabilidad.

## Proyecto

En este proyecto trabajará con la base de datos del proyecto *Cooperative Congressional Election Study*, un estudio que capturó la opinión de ciudadanos estadounidenses sobre diversos aspectos de la política y la vida pública de esa nación en 2010, 2012 y 2014. En este proyecto, buscamos conocer la relación que hay entre la aprobación del presidente en turno, Barack Obama, y la condición de empleo.

Planteamos entonces el siguiente modelo econométrico: $$y_{it} = \alpha_i +\beta empleo_{it} + BX_{it} +\varepsilon_{it}$$

[En esta liga](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TOE8I1) encontrará la base de datos y el catálogo de variables.

La base de datos contiene 1,629 columnas, pero no todas se usarán en este proyecto. Recomiendo usar las siguientes:

- Las variables **CC10_308a**, **CC12_308a** y **CC14_308a** representan la aprobación del presidente Obama en una escala del 1 al 5 (revisar el catálogo de variables). Deberá elegir cómo codificar la aprobación para construir $y_{it}$. Por ejemplo, puede colapsar las distintas categorías en dos: aprueba y desaprueba.

- Las variables que comienzan con **marstat**, **child18num** representan el estado civil y el número de hijos menores de 18 años, respectivamente. Estás variables serán los controles incluidos en $X_{it}$. ¿Por qué no usar otros controles como sexo, raza y educación?

- Las variables que comienzan con **employ** indican el estatus ocupacional. Deberá elegir cómo codificar esta variable para construir $empleo_{it}$. Por ejemplo, puede colapsar las distintas categorías en dos: empleado (si tiene un empleo de tiempo completo) y no empleado (en cualquier otro caso.

En su reporte, responda a la pregunta de cómo afecta la condición de empleo a la aprobación del presidente Obama usando tres estimadores:

1. Reporte la estimación de la relación de interés usando un estimador *pooled* e indique bajo qué condiciones el vector de parámetros estimados es consistente. Indique qué tipo de errores estándar eligió estimar y por qué.
1. Reporte la estimación de la relación de interés usando un estimador de efectos aleatorios e indique bajo qué condiciones el vector de parámetros estimados es consistente. Indique qué tipo de errores estándar eligió estimar y por qué.
1. Reporte la estimación de la relación de interés usando un estimador de efectos fijos e indique bajo qué condiciones el vector de parámetros estimados es consistente. Indique qué tipo de errores estándar eligió estimar y por qué.
