<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Respuestas a la tarea 4 – Econometría II 2024</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Respuestas a la tarea 4</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../iconoEconometria.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/rojasirvin/econometria-ii" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../programa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programa</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reglas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reglas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecturas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecturas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentaciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentaciones</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cronograma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronograma</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tareas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tareas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../diapositivas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diapositivas</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#respuestas" id="toc-respuestas" class="nav-link active" data-scroll-target="#respuestas">Respuestas</a>
  <ul class="collapse">
  <li><a href="#pregunta-1" id="toc-pregunta-1" class="nav-link" data-scroll-target="#pregunta-1">Pregunta 1</a></li>
  <li><a href="#pregunta-2" id="toc-pregunta-2" class="nav-link" data-scroll-target="#pregunta-2">Pregunta 2</a></li>
  <li><a href="#pregunta-3" id="toc-pregunta-3" class="nav-link" data-scroll-target="#pregunta-3">Pregunta 3</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Respuestas a la tarea 4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="respuestas" class="level1">
<h1>Respuestas</h1>
<section id="pregunta-1" class="level2">
<h2 class="anchored" data-anchor-id="pregunta-1">Pregunta 1</h2>
<p>Considere los datos en el archivo <em>capital_trabajo.csv</em>. Con una función de producción Cobb-Douglas las participaciones del capital y el trabajo en el valor de la producción se pueden estimar usando una regresión lineal. En algunas aplicaciones es de interés conocer el cociente de las participaciones estimadas.</p>
<ol type="a">
<li><p>[10 puntos] Usando 500 repeticiones bootstrap estime el error estándar del cociente capital-trabajo. Para ello realice el siguiente procedimiento:</p>
<ol type="i">
<li>Genere una matriz vacía de 500 filas para coleccionar sus relaciones estimadas.</li>
<li>En cada una de las repeticiones obtenga una muestra con remplazo a partir de la muestra original.</li>
<li>Estime por MCO los coeficientes sobre el log del capital y el log del trabajo. La variable dependiente es el log del valor de la producción. Calcule el cociente de los coeficientes estimados. Guarde el cociente en la matriz.</li>
<li>Repita ii. y iii. 500 veces.</li>
<li>Calcule la desviación estándar de los cocientes estimados.</li>
</ol>
<p><em>En cada repetición bootstrap debemos estimar el siguiente modelo y obtener el ratio de los coeficientes:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data.kl <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../files/capital_trabajo.csv"</span>) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lvalor <span class="sc">~</span> lcapital <span class="sc">+</span> ltrabajo, <span class="at">data=</span>data.kl))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lvalor ~ lcapital + ltrabajo, data = data.kl)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.53523 -0.25678  0.03835  0.26003  0.49631 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 10.56478    0.05303  199.24   &lt;2e-16 ***
lcapital     0.38502    0.03072   12.53   &lt;2e-16 ***
ltrabajo     0.66108    0.02813   23.50   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2999 on 97 degrees of freedom
Multiple R-squared:  0.8768, Adjusted R-squared:  0.8742 
F-statistic: 345.1 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><em>Fijamos una semilla y los parámetros de la rutina:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">120</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>B<span class="ot">=</span><span class="dv">500</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data.kl)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">beta=</span><span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> B))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Realizamos la regresión y el cálculo del cociente en cada una de las <span class="math inline">\(b\)</span> repeticiones:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  data.b <span class="ot">&lt;-</span>data.kl[<span class="fu">sample</span>(<span class="fu">nrow</span>(data.kl),obs, <span class="at">replace =</span> <span class="cn">TRUE</span>),]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Corremos regresión</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  m<span class="ot">&lt;-</span><span class="fu">lm</span>(lvalor <span class="sc">~</span> lcapital <span class="sc">+</span> ltrabajo,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">data=</span>data.b)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Guardamos en cada entrada el ratio estimado</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  beta[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(m<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">/</span> m<span class="sc">$</span>coefficients[<span class="dv">3</span>])</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>El error estimado es simplemente la desviación estándar de los B estadísticos estimados:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(beta<span class="sc">$</span>beta)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05090312</code></pre>
</div>
</div>
<p><em>El error estándar estimado es de 0.0509.</em></p></li>
<li><p>[10 puntos] Calcule ahora el error estándar jackknife, para lo que realizará <span class="math inline">\(N\)</span> estimaciones de la ecuación del valor de la producción y en cada una de ellas calculará el cociente de interés. En cada una de las <span class="math inline">\(i=1,\ldots,N\)</span> repeticiones, eliminará de la muestra la observación <span class="math inline">\(i\)</span>, por lo que cada regresión será estimada con <span class="math inline">\(N-1\)</span> observaciones. Obtenga la desviación estándar de los <span class="math inline">\(N\)</span> cocientes estimados.</p>
<p><em>Fijamo utina:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>beta.jackknife <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">beta.jackknife=</span><span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="fu">nrow</span>(data.kl)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>En cada repetición eliminamos la <span class="math inline">\(i\)</span>-ésima observación, estimamos la regresión y calculamos el cociente de interés:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data.kl))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  data.j <span class="ot">&lt;-</span> data.kl <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">row_number</span>() <span class="sc">==</span> i )</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Corremos regresión</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span><span class="fu">lm</span>(lvalor <span class="sc">~</span> lcapital <span class="sc">+</span> ltrabajo,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>data.j)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Guardamos en cada entrada el ratio estimado</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  beta.jackknife[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(m<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">/</span> m<span class="sc">$</span>coefficients[<span class="dv">3</span>])</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Obtenemos el error estándar. En clase quizás nos faltó ver la fórmula del error estándar, pero es la siguiente:</em></p>
<p><span class="math display">\[ee(\hat{\theta}_{jackknife})=\sqrt{\frac{N-1}{N}\sum_{i=1}^{N}(\hat\theta_{-i}-\bar{\hat\theta})^2}\]</span></p>
<p><em>donde <span class="math inline">\(\hat\theta_{-i}\)</span> es el estadístico estimado usando la muestra que omite la <span class="math inline">\(i\)</span>-ésima observación y <span class="math inline">\(\bar{\hat\theta}\)</span> es la media de los <span class="math inline">\(N\)</span> estadísticos estimados.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>beta.jackknife <span class="ot">&lt;-</span> beta.jackknife <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mean.beta =</span> <span class="fu">mean</span>(beta.jackknife),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sq.desv =</span> (beta.jackknife <span class="sc">-</span> mean.beta)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(((<span class="fu">nrow</span>(data.kl)<span class="sc">-</span><span class="dv">1</span>) <span class="sc">/</span> <span class="fu">nrow</span>(data.kl))<span class="sc">*</span><span class="fu">sum</span>(beta.jackknife<span class="sc">$</span>sq.desv))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04807774</code></pre>
</div>
</div>
<p><em>El error jackknife resulta ser 0.048.</em></p></li>
<li><p>[10 puntos] Compruebe que sus cálculos aproximan el error estándar obtenido con el Método Delta. Para ello, después de estimar la ecuación del valor de la producción con la muestra original, use la función <em>deltaMethod</em> del paquete <em>car</em>.</p>
<p><em>Si usamos el método Delta para calcular el error estándar de la combinación no lineal, obtenemos algo muy parecido, 0.052</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deltaMethod</span>(m1, <span class="st">"lcapital/ltrabajo"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate       SE    2.5 % 97.5 %
lcapital/ltrabajo 0.582406 0.051923 0.480639 0.6842</code></pre>
</div>
</div></li>
</ol>
</section>
<section id="pregunta-2" class="level2">
<h2 class="anchored" data-anchor-id="pregunta-2">Pregunta 2</h2>
<p>Considere los datos en <em>MunichRent.rda</em>. Estos archivos contienen información sobre rentas en la ciudad de Munich, <strong>rent</strong>. Se desea explicar la renta en función de la antiguedad de los edificios en renta, controlando por el área, <strong>area</strong>. La variable <strong>yearc</strong> indica cuándo fue construido el edificio. Construya la antiguedad como <em>antiguedad=2023-yearc</em>. Para leer los datos basta con ejecutar <em>load(“MunichRent.rda”)</em>.</p>
<ol type="a">
<li><p>[10 puntos] Estime por MCO la relación entre la renta, <strong>rent</strong> y la antiguedad del edificio, controlando por <strong>area</strong> y efectos fijos de <strong>bath</strong> y <strong>kitchen</strong>. Interprete el coeficiente sobre la antiguedad.</p>
<p><em>Primero por MCO obtenemos una relación positiva entre la renta y el área y una relación negativa entre la renta y la antiguedad, como era de esperarse. Ambos coeficientes estimados son estadísticamente significativos.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"../files/MunichRent.rda"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>MunichRent <span class="ot">&lt;-</span> MunichRent <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">antiguedad=</span><span class="dv">2023</span><span class="sc">-</span>yearc)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Por MCO</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r.mco <span class="ot">&lt;-</span> <span class="fu">lm</span>(rent  <span class="sc">~</span> area <span class="sc">+</span> antiguedad,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>MunichRent))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rent ~ area + antiguedad, data = MunichRent)

Residuals:
    Min      1Q  Median      3Q     Max 
-734.76  -94.75  -10.87   82.55 1063.17 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 264.3407    10.3561   25.52   &lt;2e-16 ***
area          5.3618     0.1165   46.01   &lt;2e-16 ***
antiguedad   -2.4913     0.1239  -20.11   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 149.3 on 3079 degrees of freedom
Multiple R-squared:  0.4181, Adjusted R-squared:  0.4177 
F-statistic:  1106 on 2 and 3079 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></li>
<li><p>[10 puntos] Estime la misma relación que en la parte a., pero con una regresión mediana. Interprete el coeficiente sobre la antiguedad.</p>
<p><em>Ahora realizamos un modelo LAD</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r.q50 <span class="ot">&lt;-</span> <span class="fu">rq</span>(rent  <span class="sc">~</span> area <span class="sc">+</span> antiguedad,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>MunichRent,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">tau=</span><span class="fl">0.5</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: rq(formula = rent ~ area + antiguedad, tau = 0.5, data = MunichRent)

tau: [1] 0.5

Coefficients:
            Value     Std. Error t value   Pr(&gt;|t|) 
(Intercept) 310.17202  11.60978   26.71643   0.00000
area          4.97688   0.14688   33.88284   0.00000
antiguedad   -3.02031   0.14599  -20.68795   0.00000</code></pre>
</div>
</div>
<p><em>Los coeficientes estimados son de una magnitud similar a los de MCO.</em></p></li>
<li><p>[10 puntos] Estime ahora una regresión cuantil para cada uno de los deciles de la distribución condicional de la renta y represente en una gráfica los coeficientes por regresión cuantil junto con el coeficiente de MCO para las variables del área y la antiguedad. ¿Concluye que vale la pena modelar la relación de las rentas en función del área y la antiguedad usando regresión cuantil?</p>
<p><em>Regresión cuantil para cada decil:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>r.q1_9 <span class="ot">&lt;-</span> <span class="fu">rq</span>(rent  <span class="sc">~</span> area <span class="sc">+</span> antiguedad,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>MunichRent,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">tau=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span><span class="sc">/</span><span class="dv">10</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(r.q1_9), <span class="at">parm=</span><span class="fu">c</span>(<span class="st">"area"</span>,<span class="st">"antiguedad"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Los efectos de la antiguedad en la distribución de precios son no lineales. Los efectos en los cuantiles superiores crecen más rápido con la antiguedad. Quizás esto sugiera una preferencia por edificios viejos. La regresión cuantil sí fue útil para revelar esta característica.</em></p></li>
<li><p>[10 puntos] Suponga que no está dispuesto a imponer una relación lineal entre la antiguedad y la renta. Considere entonces el siguiente modelo:</p>
<p><span class="math display">\[rent_i=\beta_0+\beta_1 area + \lambda(antiguedad_i)+\varepsilon_i\]</span></p>
<p>Use el estimador de Robinson (1988) para estimar este modelo parcialmente lineal. Grafique sus resultados e interprételos.</p>
<p><em>Seleccionamos el ancho de banda:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">npplregbw</span>(<span class="at">formula=</span>rent <span class="sc">~</span> area <span class="sc">|</span> antiguedad,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>MunichRent,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">regtype=</span><span class="st">"ll"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Implementamos el estimador de Robinson:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model.pl <span class="ot">&lt;-</span> <span class="fu">npplreg</span>(bw)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.pl)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Partially Linear Model
Regression data: 3082 training points, in 2 variable(s)
With 1 linear parametric regressor(s), 1 nonparametric regressor(s)

                  y(z)
Bandwidth(s): 2.368969

                   x(z)
Bandwidth(s): 0.8672961

                    area
Coefficient(s): 5.143053

Kernel Regression Estimator: Local-Linear
Bandwidth Type: Fixed

Residual standard error: 145.801
R-squared: 0.4445272

Continuous Kernel Type: Second-Order Gaussian
No. Continuous Explanatory Vars.: 1</code></pre>
</div>
</div>
<p><em>Para obtener el gráfico usamos npplot:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>g.robinson <span class="ot">&lt;-</span> <span class="fu">npplot</span>(bw,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">perspective=</span>F,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot.errors.method=</span><span class="st">"bootstrap"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot.errors.boot.num=</span><span class="dv">5</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot.behavior=</span><span class="st">"plot-data"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">fitted</span>(g.robinson<span class="sc">$</span>plr2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> g.robinson[[<span class="st">"plr2"</span>]][[<span class="st">"merr"</span>]]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>lci <span class="ot">&lt;-</span> g <span class="sc">-</span> se[,<span class="dv">1</span>]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>uci <span class="ot">&lt;-</span> g <span class="sc">+</span> se[,<span class="dv">2</span>]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Este objeto nos dicen dónde fueron evaluados</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>antiguedad.eval <span class="ot">&lt;-</span> g.robinson[[<span class="st">"plr2"</span>]][[<span class="st">"evalz"</span>]][[<span class="st">"V1"</span>]]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>fitted <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(antiguedad.eval, g,lci,uci)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>MunichRent, <span class="fu">aes</span>(antiguedad,rent), <span class="at">color=</span><span class="st">'black'</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>fitted, <span class="fu">aes</span>(antiguedad.eval, g), <span class="at">linetype=</span><span class="st">'solid'</span>)<span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>fitted, <span class="fu">aes</span>(antiguedad.eval, uci), <span class="at">linetype=</span><span class="st">'dashed'</span>)<span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>fitted, <span class="fu">aes</span>(antiguedad.eval, lci), <span class="at">linetype=</span><span class="st">'dashed'</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
</section>
<section id="pregunta-3" class="level2">
<h2 class="anchored" data-anchor-id="pregunta-3">Pregunta 3</h2>
<p><a href="https://academic.oup.com/qje/article-abstract/121/1/267/1849020">Stevenson &amp; Wolfers (2006)</a> estudian los efectos de la introducción de leyes que permiten el divorcio unilateral. La librería <em>bacondecomp</em> incluye los datos usados en dicho artículo. Usaremos los datos de 1964 a 1996 para mostrar cómo impactan las leyes de divorcio express (unilateral) a la tasa de suicidios en mujeres. Comience llamando los datos:</p>
<p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>wd <span class="ot">&lt;-</span> divorce <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">&gt;</span><span class="dv">1964</span> <span class="sc">&amp;</span> year<span class="sc">&lt;</span><span class="dv">1996</span> <span class="sc">&amp;</span> sex<span class="sc">==</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">suicide_rate=</span>suicide<span class="sc">*</span><span class="dv">1000000</span><span class="sc">/</span>(stpop<span class="sc">*</span>fshare),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">year=</span><span class="fu">as.numeric</span>(year))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<ol type="a">
<li><p>[5 puntos] Estime el efecto de diferencia en diferencias asumiendo tendencias paralelas y el estimador de <em>two-way fixed effects</em>. Obtenga los errores estándar primero asumiendo errores clásicos y luego usando una matriz agrupada a nivel estado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>m.twfe <span class="ot">&lt;-</span> <span class="fu">felm</span>(suicide_rate <span class="sc">~</span> unilateral <span class="sc">|</span> <span class="fu">factor</span>(st) <span class="sc">+</span> <span class="fu">factor</span>(year),</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> wd)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>m.twfe.cl <span class="ot">&lt;-</span> <span class="fu">felm</span>(suicide_rate <span class="sc">~</span> unilateral <span class="sc">|</span> <span class="fu">factor</span>(st) <span class="sc">+</span> <span class="fu">factor</span>(year) <span class="sc">|</span> <span class="dv">0</span> <span class="sc">|</span> st,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> wd)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="at">models =</span> <span class="fu">list</span>(<span class="st">"TWFE"</span><span class="ot">=</span>m.twfe,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"TWFE, agrupada"</span><span class="ot">=</span>m.twfe.cl),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_map =</span> <span class="fu">c</span>(<span class="st">'unilateral'</span>),</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">output =</span> <span class="st">'gt'</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">stars =</span> <span class="fu">c</span>(<span class="st">'***'</span> <span class="ot">=</span> .<span class="dv">01</span>, <span class="st">'**'</span> <span class="ot">=</span> .<span class="dv">05</span>, <span class="st">'*'</span> <span class="ot">=</span> <span class="fl">0.1</span>),</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">gof_map =</span> <span class="st">"nobs"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="hlpfxfzlpp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hlpfxfzlpp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hlpfxfzlpp thead, #hlpfxfzlpp tbody, #hlpfxfzlpp tfoot, #hlpfxfzlpp tr, #hlpfxfzlpp td, #hlpfxfzlpp th {
  border-style: none;
}

#hlpfxfzlpp p {
  margin: 0;
  padding: 0;
}

#hlpfxfzlpp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hlpfxfzlpp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hlpfxfzlpp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hlpfxfzlpp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hlpfxfzlpp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hlpfxfzlpp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlpfxfzlpp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hlpfxfzlpp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hlpfxfzlpp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hlpfxfzlpp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hlpfxfzlpp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hlpfxfzlpp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hlpfxfzlpp .gt_spanner_row {
  border-bottom-style: hidden;
}

#hlpfxfzlpp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hlpfxfzlpp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hlpfxfzlpp .gt_from_md > :first-child {
  margin-top: 0;
}

#hlpfxfzlpp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hlpfxfzlpp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hlpfxfzlpp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hlpfxfzlpp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hlpfxfzlpp .gt_row_group_first td {
  border-top-width: 2px;
}

#hlpfxfzlpp .gt_row_group_first th {
  border-top-width: 2px;
}

#hlpfxfzlpp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlpfxfzlpp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hlpfxfzlpp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hlpfxfzlpp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlpfxfzlpp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlpfxfzlpp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hlpfxfzlpp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hlpfxfzlpp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hlpfxfzlpp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hlpfxfzlpp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hlpfxfzlpp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlpfxfzlpp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hlpfxfzlpp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hlpfxfzlpp .gt_left {
  text-align: left;
}

#hlpfxfzlpp .gt_center {
  text-align: center;
}

#hlpfxfzlpp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hlpfxfzlpp .gt_font_normal {
  font-weight: normal;
}

#hlpfxfzlpp .gt_font_bold {
  font-weight: bold;
}

#hlpfxfzlpp .gt_font_italic {
  font-style: italic;
}

#hlpfxfzlpp .gt_super {
  font-size: 65%;
}

#hlpfxfzlpp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hlpfxfzlpp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hlpfxfzlpp .gt_indent_1 {
  text-indent: 5px;
}

#hlpfxfzlpp .gt_indent_2 {
  text-indent: 10px;
}

#hlpfxfzlpp .gt_indent_3 {
  text-indent: 15px;
}

#hlpfxfzlpp .gt_indent_4 {
  text-indent: 20px;
}

#hlpfxfzlpp .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id=" " class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="TWFE" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">TWFE</th>
<th id="TWFE, agrupada" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">TWFE, agrupada</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="">unilateral</td>
<td class="gt_row gt_center" headers="TWFE">-2.824**</td>
<td class="gt_row gt_center" headers="TWFE, agrupada">-2.824</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000"></td>
<td class="gt_row gt_center" headers="TWFE" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000">(1.108)</td>
<td class="gt_row gt_center" headers="TWFE, agrupada" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000">(2.274)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="">Num.Obs.</td>
<td class="gt_row gt_center" headers="TWFE">1581</td>
<td class="gt_row gt_center" headers="TWFE, agrupada">1581</td>
</tr>
</tbody><tfoot class="gt_sourcenotes">
<tr class="even">
<td colspan="3" class="gt_sourcenote">* p &lt; 0.1, ** p &lt; 0.05, *** p &lt; 0.01</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div></li>
<li><p>[5 puntos] Realice la descomposición de Goodman-Bacon (2021). Construya un gráfico donde muestre en el eje el peso otorgado a cada comparación 2x2 que el estimador de TWFE realiza mecánicamente y en el eje el efecto estimado correspondiente a cada comparación. Interprete el gráfico obtenido.</p>
<p><em>Implementamos la descomposición:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_bacon <span class="ot">&lt;-</span> <span class="fu">bacon</span>(suicide_rate <span class="sc">~</span> unilateral,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> wd,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">id_var =</span> <span class="st">"st"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">time_var =</span> <span class="st">"year"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      type  weight  avg_est
1 Earlier vs Later Treated 0.10544  1.70904
2  Later vs Always Treated 0.39872 -6.72231
3 Later vs Earlier Treated 0.27432  3.31462
4     Treated vs Untreated 0.22151 -5.56686</code></pre>
</div>
</div>
<p><em>La tabla anterior nos da los valores de los estimadores <span class="math inline">\(2\times 2\)</span> con sus correspondientes pesos. El promedio ponderado es exactamente el estimador de efectos fijos:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>coef_bacon <span class="ot">&lt;-</span> <span class="fu">sum</span>(df_bacon<span class="sc">$</span>estimate <span class="sc">*</span> df_bacon<span class="sc">$</span>weight)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Suma ponderada de la descomposición ="</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">round</span>(coef_bacon, <span class="dv">4</span>)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Suma ponderada de la descomposición = -2.824"</code></pre>
</div>
</div>
<p><em>Construimos el gráfico:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_bacon <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>weight,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y=</span>estimate,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span>type,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">color=</span>type)) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">round</span>(m.twfe<span class="sc">$</span>coefficients, <span class="dv">4</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Las comparaciones que más pesan en el estimador de efectos fijos son las de estados tratados con los que siempre estuvieron tratados en el panel, recibiendo dos de esas comparaciones alrededor de 12.5 y el 6% del peso (los dos triángulos verdes más hacia la derecha). otra comparación que recibe alrededor de 6.5% del peso es la de los tratados con los nunca tratados (cruz morada más hacia la derecha). En total, las comparaciones con estados que iniciaron siendo tratados se llevan el 40% del peso. Las comparaciones entre los tratados tarde y los tratados temprano también reciben un peso alto de 27%.</em></p></li>
<li><p>[10 puntos] Implemente el estimador de Callaway &amp; Sant’Anna (2021) para estimar los efectos del tratamiento específicos para cada cohorte, usando el paquete <em>did</em>. Utilice como grupo de comparación los estados <em>que nunca son tratados</em>. La columna <strong>stid</strong> es un identificador numérico de los estados (lo requerirá cuando use <em>att_gt</em> del paquete <em>did</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>atts_nt <span class="ot">&lt;-</span> <span class="fu">att_gt</span>(<span class="at">yname =</span> <span class="st">"suicide_rate"</span>,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tname =</span> <span class="st">"year"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">idname =</span> <span class="st">"stid"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">gname =</span> <span class="st">"divyear"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> wd,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">control_group =</span> <span class="st">"nevertreated"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">est_method =</span> <span class="st">'reg'</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">bstrap =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">biters =</span> <span class="dv">1000</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">print_details =</span> <span class="cn">FALSE</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">panel =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(atts_nt)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
att_gt(yname = "suicide_rate", tname = "year", idname = "stid", 
    gname = "divyear", data = wd, panel = TRUE, control_group = "nevertreated", 
    bstrap = TRUE, biters = 1000, est_method = "reg", print_details = FALSE)

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 

Group-Time Average Treatment Effects:
 Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]  
  1969 1966  -3.1857    12.6090      -50.6076     44.2362  
  1969 1967  12.5043     8.8492      -20.7772     45.7858  
  1969 1968   3.1310     7.6435      -25.6160     31.8780  
  1969 1969   1.1566     6.5207      -23.3675     25.6808  
  1969 1970  -3.5412    13.3245      -53.6543     46.5720  
  1969 1971  -6.7647    11.7616      -50.9995     37.4702  
  1969 1972   1.7696    11.2775      -40.6447     44.1838  
  1969 1973   2.7611     7.6039      -25.8369     31.3591  
  1969 1974  -0.3084     8.5271      -32.3787     31.7618  
  1969 1975  -0.7421     5.0161      -19.6075     18.1234  
  1969 1976 -10.6073     7.5492      -38.9994     17.7848  
  1969 1977  -3.9320    12.0431      -49.2258     41.3619  
  1969 1978 -14.0099    11.3649      -56.7528     28.7329  
  1969 1979  -8.1059    13.5501      -59.0675     42.8556  
  1969 1980 -10.6943     7.3175      -38.2150     16.8265  
  1969 1981  -3.4755    12.1039      -48.9980     42.0469  
  1969 1982  -7.0072     9.0613      -41.0864     27.0721  
  1969 1983   5.1998    13.3936      -45.1733     55.5728  
  1969 1984 -10.0771    13.3542      -60.3017     40.1474  
  1969 1985   5.9598    17.2201      -58.8045     70.7240  
  1969 1986  -8.5962    12.7169      -56.4240     39.2317  
  1969 1987  -8.6897     7.7323      -37.7705     20.3911  
  1969 1988 -11.9815     8.3038      -43.2119     19.2489  
  1969 1989  -5.9781    15.2884      -63.4774     51.5213  
  1969 1990  -7.7327    11.1956      -49.8389     34.3735  
  1969 1991 -14.7659    11.4140      -57.6934     28.1616  
  1969 1992  -6.6956     6.5026      -31.1515     17.7603  
  1969 1993   0.5290    12.8492      -47.7963     48.8543  
  1969 1994  -6.1575    16.2005      -67.0872     54.7721  
  1969 1995  -6.7870    17.1863      -71.4242     57.8503  
  1970 1966  -5.7213     9.5945      -41.8061     30.3635  
  1970 1967  10.0224     8.7761      -22.9842     43.0289  
  1970 1968  -5.3764     9.3571      -40.5682     29.8154  
  1970 1969  10.5202     6.3007      -13.1766     34.2169  
  1970 1970   5.6377     6.5355      -18.9419     30.2174  
  1970 1971   1.3987     4.8790      -16.9511     19.7485  
  1970 1972   1.3331     9.6135      -34.8230     37.4891  
  1970 1973 -13.0254     3.8835      -27.6311      1.5803  
  1970 1974 -12.7744     4.9304      -31.3173      5.7685  
  1970 1975 -15.3434     4.8741      -33.6748      2.9880  
  1970 1976 -19.8605     4.0152      -34.9616     -4.7594 *
  1970 1977 -19.5551     6.0573      -42.3365      3.2263  
  1970 1978 -33.3382     5.6337      -54.5265    -12.1499 *
  1970 1979 -30.5087    13.5303      -81.3955     20.3781  
  1970 1980 -44.6366     7.4756      -72.7523    -16.5210 *
  1970 1981 -34.0557    11.3256      -76.6509      8.5395  
  1970 1982 -38.7875    10.3941      -77.8796      0.3045  
  1970 1983 -32.9234    17.1234      -97.3240     31.4771  
  1970 1984 -34.0625    11.3245      -76.6535      8.5286  
  1970 1985 -30.6346    19.1149     -102.5252     41.2560  
  1970 1986 -37.0754    18.8397     -107.9311     33.7802  
  1970 1987 -37.6630    11.4929      -80.8875      5.5615  
  1970 1988 -43.0563    12.8519      -91.3921      5.2794  
  1970 1989 -45.1314    14.6881     -100.3729     10.1101  
  1970 1990 -43.1765     8.6367      -75.6588    -10.6942 *
  1970 1991 -49.9116     9.3412      -85.0436    -14.7797 *
  1970 1992 -50.9515    14.7946     -106.5937      4.6906  
  1970 1993 -44.5526    12.3309      -90.9285      1.8233  
  1970 1994 -51.5405    17.6950     -118.0909     15.0099  
  1970 1995 -48.4108    17.3598     -113.7003     16.8788  
  1971 1966 -12.4375     9.2619      -47.2712     22.3963  
  1971 1967  17.0967     8.3386      -14.2643     48.4578  
  1971 1968   2.6186     7.3020      -24.8440     30.0813  
  1971 1969  -2.1268     5.6673      -23.4413     19.1876  
  1971 1970   5.7625     6.9692      -20.4485     31.9734  
  1971 1971  -9.3866     7.2642      -36.7071     17.9338  
  1971 1972 -13.8393     7.9538      -43.7533     16.0746  
  1971 1973 -12.4602     7.8160      -41.8558     16.9355  
  1971 1974   0.1729     5.5446      -20.6803     21.0261  
  1971 1975  -8.8785     7.9118      -38.6345     20.8775  
  1971 1976  -7.7923     5.8002      -29.6065     14.0219  
  1971 1977  -6.3192     8.1699      -37.0460     24.4077  
  1971 1978 -17.4985    10.5786      -57.2843     22.2872  
  1971 1979 -16.1999     5.9721      -38.6606      6.2609  
  1971 1980 -22.5395     5.3023      -42.4812     -2.5978 *
  1971 1981 -12.5894     8.1475      -43.2319     18.0532  
  1971 1982 -20.6385    10.2477      -59.1799     17.9028  
  1971 1983 -11.0888     5.8593      -33.1253     10.9477  
  1971 1984 -12.7478     6.1768      -35.9787     10.4831  
  1971 1985  -9.3683     8.7995      -42.4627     23.7262  
  1971 1986 -16.9260     7.0962      -43.6145      9.7625  
  1971 1987 -12.9962    10.8822      -53.9237     27.9313  
  1971 1988 -14.6487     8.1038      -45.1267     15.8292  
  1971 1989 -18.7126     9.6051      -54.8369     17.4118  
  1971 1990 -17.6198     6.9975      -43.9371      8.6976  
  1971 1991 -17.2789     8.8508      -50.5665     16.0088  
  1971 1992 -22.1825     9.5658      -58.1592     13.7943  
  1971 1993  -9.1278     9.4625      -44.7159     26.4603  
  1971 1994 -13.7091     8.6761      -46.3396     18.9214  
  1971 1995 -15.3270     7.1781      -42.3235     11.6695  
  1972 1966  -5.2709    10.2345      -43.7627     33.2209  
  1972 1967   8.3599     9.5882      -27.7009     44.4207  
  1972 1968   5.3444     7.4435      -22.6504     33.3393  
  1972 1969  -6.1540     5.3925      -26.4352     14.1272  
  1972 1970   5.3754     5.4766      -15.2220     25.9729  
  1972 1971  -0.7708     5.3490      -20.8882     19.3467  
  1972 1972  -5.3078     4.8366      -23.4980     12.8824  
  1972 1973  -7.1261     9.2918      -42.0722     27.8199  
  1972 1974  -4.3635     4.5454      -21.4585     12.7315  
  1972 1975 -10.7104     7.0424      -37.1965     15.7756  
  1972 1976  -8.5659     7.7610      -37.7548     20.6229  
  1972 1977  -1.7264     4.1491      -17.3312     13.8784  
  1972 1978 -19.5471     7.8113      -48.9251      9.8310  
  1972 1979  -9.7870    10.2059      -48.1712     28.5972  
  1972 1980 -16.4149     6.0669      -39.2322      6.4024  
  1972 1981  -4.6831     4.8897      -23.0731     13.7069  
  1972 1982  -9.8129     8.9395      -43.4339     23.8082  
  1972 1983  -5.7570     6.8767      -31.6201     20.1061  
  1972 1984 -11.1817     5.6138      -32.2949      9.9314  
  1972 1985  -8.5492     8.7787      -41.5657     24.4672  
  1972 1986  -3.2909     6.2836      -26.9234     20.3416  
  1972 1987 -14.5853     7.4985      -42.7867     13.6162  
  1972 1988 -12.6795     6.3039      -36.3883     11.0293  
  1972 1989 -10.9845     7.1656      -37.9340     15.9651  
  1972 1990  -7.7794     7.3159      -35.2943     19.7355  
  1972 1991 -13.7033     5.5948      -34.7451      7.3385  
  1972 1992 -11.0100     8.8163      -44.1679     22.1480  
  1972 1993 -17.3770     7.4747      -45.4890     10.7350  
  1972 1994 -16.6543     7.9092      -46.4007     13.0920  
  1972 1995 -16.0626     6.6801      -41.1862      9.0610  
  1973 1966 -10.0893    10.0711      -47.9663     27.7876  
  1973 1967  16.0570     9.7318      -20.5439     52.6580  
  1973 1968  -4.8486     8.5848      -37.1357     27.4385  
  1973 1969   3.3129     6.0442      -19.4192     26.0449  
  1973 1970   5.5555     6.4672      -18.7676     29.8786  
  1973 1971  -2.0683     7.2951      -29.5049     25.3683  
  1973 1972  -0.9275     6.5936      -25.7258     23.8707  
  1973 1973   4.4106     8.4384      -27.3258     36.1470  
  1973 1974   3.2944     6.1162      -19.7086     26.2973  
  1973 1975   0.0725    11.5704      -43.4432     43.5883  
  1973 1976  -1.1180     6.2547      -24.6418     22.4059  
  1973 1977   2.7203     5.8664      -19.3431     24.7837  
  1973 1978 -10.3862     8.7687      -43.3649     22.5924  
  1973 1979  -3.4722     7.2328      -30.6746     23.7303  
  1973 1980 -11.7465     7.7766      -40.9940     17.5009  
  1973 1981  -3.1322     7.4260      -31.0614     24.7969  
  1973 1982  -7.8264    10.3198      -46.6387     30.9859  
  1973 1983  -4.3281     5.9254      -26.6134     17.9572  
  1973 1984 -10.3847     6.4512      -34.6474     13.8780  
  1973 1985  -3.3503     7.6448      -32.1021     25.4014  
  1973 1986  -9.9416     4.6451      -27.4118      7.5286  
  1973 1987 -10.5611     8.6734      -43.1813     22.0591  
  1973 1988 -13.3770     9.0506      -47.4158     20.6619  
  1973 1989  -9.7072     6.9669      -35.9096     16.4952  
  1973 1990 -12.5464     6.0032      -35.1243     10.0314  
  1973 1991 -15.9396     7.1237      -42.7317     10.8526  
  1973 1992 -17.9985     6.9073      -43.9765      7.9796  
  1973 1993 -13.8426     7.8503      -43.3673     15.6821  
  1973 1994  -9.0985     6.0048      -31.6824     13.4855  
  1973 1995 -12.4104     4.0223      -27.5381      2.7173  
  1974 1966  -3.7313    10.2818      -42.4010     34.9383  
  1974 1967   9.6967     8.4315      -22.0140     41.4075  
  1974 1968  -5.6736     8.2589      -36.7351     25.3879  
  1974 1969   4.7497     5.0947      -14.4114     23.9108  
  1974 1970   8.9528     5.5731      -12.0073     29.9129  
  1974 1971  -8.1562     5.5379      -28.9842     12.6718  
  1974 1972   5.1631     4.2741      -10.9115     21.2378  
  1974 1973  -4.1358     7.3372      -31.7309     23.4592  
  1974 1974  -1.5277     4.6118      -18.8727     15.8173  
  1974 1975  -0.2490     4.8780      -18.5948     18.0968  
  1974 1976  -4.6623     3.9210      -19.4090     10.0844  
  1974 1977  -3.6545     7.2230      -30.8199     23.5110  
  1974 1978  -9.4996     5.6922      -30.9080     11.9087  
  1974 1979  -1.7953     9.8989      -39.0246     35.4340  
  1974 1980 -10.9157     5.3459      -31.0215      9.1901  
  1974 1981  -2.9438     7.4216      -30.8561     24.9686  
  1974 1982  -6.1358     5.0386      -25.0859     12.8143  
  1974 1983  -2.2347     7.6185      -30.8878     26.4184  
  1974 1984  -7.2784     6.5728      -31.9986     17.4418  
  1974 1985   0.9048    10.7007      -39.3403     41.1500  
  1974 1986  -3.4953     8.9151      -37.0248     30.0342  
  1974 1987  -9.3045     8.3304      -40.6350     22.0259  
  1974 1988  -9.0434     8.4419      -40.7932     22.7063  
  1974 1989  -6.4758     9.6869      -42.9080     29.9564  
  1974 1990  -7.6369     8.1137      -38.1521     22.8783  
  1974 1991 -14.7133     7.9173      -44.4900     15.0634  
  1974 1992 -14.7711     7.9707      -44.7486     15.2064  
  1974 1993 -11.2274     8.5024      -43.2045     20.7497  
  1974 1994 -14.4350    10.7449      -54.8461     25.9761  
  1974 1995 -13.4194     9.6698      -49.7871     22.9484  
  1975 1966 -10.7092     9.4775      -46.3536     24.9352  
  1975 1967   9.6526     8.5008      -22.3186     41.6237  
  1975 1968   5.2146     7.9016      -24.5031     34.9324  
  1975 1969  -2.1343     8.3120      -33.3954     29.1269  
  1975 1970  -5.6035     9.4988      -41.3283     30.1214  
  1975 1971   3.4917     9.6360      -32.7492     39.7325  
  1975 1972 -15.0108     8.0545      -45.3036     15.2820  
  1975 1973   9.7321     7.1463      -17.1450     36.6091  
  1975 1974   0.5633     5.8727      -21.5236     22.6502  
  1975 1975  -4.9361     5.2822      -24.8023     14.9300  
  1975 1976  -1.1020     3.9490      -15.9540     13.7501  
  1975 1977  -4.3766    10.2412      -42.8934     34.1401  
  1975 1978  -8.3191     7.6221      -36.9856     20.3474  
  1975 1979 -12.7262    16.1052      -73.2973     47.8450  
  1975 1980 -12.3662     5.2244      -32.0149      7.2826  
  1975 1981  -7.7023     6.5726      -32.4217     17.0171  
  1975 1982  -9.7198     9.3131      -44.7463     25.3066  
  1975 1983  -7.3926     6.3929      -31.4359     16.6507  
  1975 1984   8.8507     9.4537      -26.7045     44.4058  
  1975 1985  -5.6163     8.3174      -36.8977     25.6651  
  1975 1986  -5.2183     4.7325      -23.0171     12.5805  
  1975 1987  -0.8638     5.2844      -20.7382     19.0107  
  1975 1988 -15.3668    14.3175      -69.2143     38.4808  
  1975 1989  -5.4933     5.8675      -27.5609     16.5742  
  1975 1990   8.5067     7.9168      -21.2680     38.2813  
  1975 1991   0.7631     5.9418      -21.5839     23.1101  
  1975 1992  -4.2255     6.0728      -27.0650     18.6140  
  1975 1993   1.1200     2.5499       -8.4702     10.7101  
  1975 1994  -8.3655     7.6252      -37.0437     20.3128  
  1975 1995   1.8041     3.8506      -12.6781     16.2863  
  1976 1966  -7.3839     9.4775      -43.0283     28.2605  
  1976 1967   6.1953     8.5008      -25.7758     38.1665  
  1976 1968  -3.4100     6.8387      -29.1299     22.3100  
  1976 1969  -4.5734     4.4373      -21.2619     12.1150  
  1976 1970  13.6356     4.7051       -4.0601     31.3313  
  1976 1971   2.1590     5.5379      -18.6690     22.9870  
  1976 1972  -1.4512     4.3507      -17.8142     14.9117  
  1976 1973 -23.5440     6.8621      -49.3521      2.2641  
  1976 1974  37.6970     4.2540       21.6977     53.6963 *
  1976 1975  -5.8620     5.1960      -25.4041     13.6801  
  1976 1976   7.3375     6.7834      -18.1745     32.8496  
  1976 1977  35.4928     7.3478        7.8581     63.1274 *
  1976 1978  -2.2158     3.3728      -14.9006     10.4690  
  1976 1979   2.7599    11.1105      -39.0265     44.5463  
  1976 1980 -10.1277     5.1657      -29.5559      9.3004  
  1976 1981  -9.1249     8.4453      -40.8873     22.6375  
  1976 1982  -9.7529     5.1867      -29.2600      9.7541  
  1976 1983 -12.2793     7.8075      -41.6431     17.0844  
  1976 1984 -20.1148     4.7838      -38.1066     -2.1229 *
  1976 1985  -0.2053    11.6139      -43.8848     43.4742  
  1976 1986 -27.7992     8.3181      -59.0832      3.4848  
  1976 1987  -9.9985     3.6973      -23.9038      3.9069  
  1976 1988 -22.8540     5.8685      -44.9254     -0.7826 *
  1976 1989 -14.3020     6.6385      -39.2692     10.6652  
  1976 1990 -16.7275     4.8656      -35.0267      1.5717  
  1976 1991 -29.9838     5.5425      -50.8290     -9.1387 *
  1976 1992 -35.9431     6.2168      -59.3241    -12.5620 *
  1976 1993 -33.5630     6.2298      -56.9932    -10.1328 *
  1976 1994 -19.1785    10.5829      -58.9804     20.6233  
  1976 1995 -18.8943     9.0197      -52.8170     15.0284  
  1977 1966 -17.8103    11.1251      -59.6516     24.0310  
  1977 1967  22.0500     9.1659      -12.4225     56.5225  
  1977 1968 -12.0551    13.0853      -61.2684     37.1582  
  1977 1969  11.3299    12.0132      -33.8514     56.5113  
  1977 1970   7.9543     7.6371      -20.7685     36.6771  
  1977 1971   0.9514     9.1138      -33.3252     35.2281  
  1977 1972  -1.0798     9.5351      -36.9411     34.7816  
  1977 1973  -2.0153     9.3763      -37.2792     33.2485  
  1977 1974 -10.4409     5.7751      -32.1610     11.2792  
  1977 1975  -2.6782     7.1322      -29.5022     24.1458  
  1977 1976   7.5869    18.0939      -60.4636     75.6373  
  1977 1977  -0.3083    15.2383      -57.6192     57.0026  
  1977 1978 -18.5991    18.2767      -87.3370     50.1389  
  1977 1979  -8.3001    28.5726     -115.7608     99.1606  
  1977 1980 -13.4381    23.5917     -102.1657     75.2895  
  1977 1981 -12.1467    21.1072      -91.5302     67.2367  
  1977 1982 -17.4639    16.5230      -79.6064     44.6786  
  1977 1983   6.1362    30.8151     -109.7585    122.0309  
  1977 1984  -2.9191    24.6110      -95.4801     89.6419  
  1977 1985 -14.8995    20.0884      -90.4513     60.6523  
  1977 1986 -12.3230    14.6294      -67.3438     42.6979  
  1977 1987 -23.6769    27.9188     -128.6785     81.3247  
  1977 1988 -25.5547    22.3801     -109.7256     58.6162  
  1977 1989  -9.2602    30.0056     -122.1103    103.5898  
  1977 1990 -13.7369    29.7268     -125.5385     98.0647  
  1977 1991 -25.9731    24.8484     -119.4270     67.4807  
  1977 1992 -29.9220    23.7594     -119.2802     59.4362  
  1977 1993 -14.9531    27.8362     -119.6441     89.7380  
  1977 1994 -11.6033    35.5769     -145.4068    122.2001  
  1977 1995 -29.0098    21.5447     -110.0389     52.0193  
  1980 1966  -9.4644     9.4775      -45.1088     26.1799  
  1980 1967  12.2092     8.5008      -19.7619     44.1804  
  1980 1968   3.0528     6.8387      -22.6672     28.7727  
  1980 1969  -3.6543     4.4373      -20.3428     13.0341  
  1980 1970  12.7725     4.7051       -4.9232     30.4682  
  1980 1971 -11.0126     5.5379      -31.8406      9.8154  
  1980 1972   5.2094     4.3507      -11.1536     21.5723  
  1980 1973  -8.0378     6.8621      -33.8459     17.7703  
  1980 1974   2.0132     4.2540      -13.9861     18.0125  
  1980 1975  -3.8913     5.1960      -23.4335     15.6508  
  1980 1976   4.9514     6.7834      -20.5607     30.4634  
  1980 1977  -1.8244     3.6248      -15.4572     11.8085  
  1980 1978  -6.3410     5.6068      -27.4279     14.7460  
  1980 1979   5.7875    10.6480      -34.2594     45.8344  
  1980 1980 -12.0465     7.0875      -38.7025     14.6095  
  1980 1981  -7.2766     3.1780      -19.2288      4.6756  
  1980 1982  -7.7888    11.4064      -50.6877     35.1102  
  1980 1983   3.8986     3.7649      -10.2611     18.0583  
  1980 1984  -2.3172     5.8716      -24.4002     19.7657  
  1980 1985   4.4467     4.7848      -13.5490     22.4423  
  1980 1986  -9.5981     7.0565      -36.1373     16.9410  
  1980 1987 -10.0537    11.0181      -51.4923     31.3849  
  1980 1988 -10.9789     9.1300      -45.3164     23.3587  
  1980 1989  -6.9527     6.3603      -30.8735     16.9681  
  1980 1990  -5.3312     6.2450      -28.8183     18.1560  
  1980 1991  -8.8820     7.9543      -38.7981     21.0340  
  1980 1992 -12.0023     8.8737      -45.3760     21.3714  
  1980 1993  -8.3192     7.7315      -37.3969     20.7586  
  1980 1994 -12.5474     7.1011      -39.2546     14.1597  
  1980 1995  -6.7308     9.4076      -42.1124     28.6508  
  1984 1966  -9.0520     9.4775      -44.6964     26.5924  
  1984 1967  10.1591     8.5008      -21.8120     42.1303  
  1984 1968  -3.1247     6.8387      -28.8447     22.5952  
  1984 1969   4.0091     4.4373      -12.6793     20.6976  
  1984 1970   4.9470     4.7051      -12.7487     22.6428  
  1984 1971 -12.3840     5.5379      -33.2120      8.4440  
  1984 1972   5.1482     4.3507      -11.2147     21.5112  
  1984 1973  -6.4124     6.8621      -32.2205     19.3957  
  1984 1974  -5.7358     4.2540      -21.7351     10.2635  
  1984 1975  -4.0919     5.1960      -23.6340     15.4503  
  1984 1976   8.7209     6.7834      -16.7911     34.2329  
  1984 1977   2.6679     3.6248      -10.9650     16.3007  
  1984 1978  -7.3955     5.6068      -28.4825     13.6914  
  1984 1979   2.2253    10.6480      -37.8217     42.2722  
  1984 1980  -8.3661     7.0875      -35.0220     18.2899  
  1984 1981  10.0008     5.6947      -11.4168     31.4184  
  1984 1982  -3.2324    10.2165      -41.6562     35.1914  
  1984 1983  11.0979    10.1458      -27.0603     49.2560  
  1984 1984  -1.6979     3.0237      -13.0697      9.6740  
  1984 1985   4.0744     3.8064      -10.2414     18.3901  
  1984 1986  -8.0341     2.9094      -18.9763      2.9081  
  1984 1987 -10.4189     7.1120      -37.1667     16.3289  
  1984 1988  -7.8277     5.4597      -28.3613     12.7059  
  1984 1989  -9.2894     3.4826      -22.3874      3.8086  
  1984 1990  -6.2529     3.0974      -17.9022      5.3963  
  1984 1991 -10.1584     4.9176      -28.6534      8.3366  
  1984 1992 -11.4694     4.6630      -29.0068      6.0680  
  1984 1993  -9.2844     4.4284      -25.9395      7.3707  
  1984 1994 -14.6630     3.4313      -27.5682     -1.7578 *
  1984 1995 -12.5044     3.3329      -25.0393      0.0304  
  1985 1966  29.3180     9.4775       -6.3263     64.9624  
  1985 1967  -6.8558     8.5008      -38.8270     25.1153  
  1985 1968  -5.9545     6.8387      -31.6745     19.7654  
  1985 1969  12.1675     4.4373       -4.5209     28.8560  
  1985 1970  12.3074     4.7051       -5.3883     30.0031  
  1985 1971   4.9424     5.5379      -15.8856     25.7704  
  1985 1972   5.1718     4.3507      -11.1911     21.5348  
  1985 1973 -41.2443     6.8621      -67.0524    -15.4362 *
  1985 1974   9.0064     4.2540       -6.9928     25.0057  
  1985 1975  -9.1424     5.1960      -28.6845     10.3998  
  1985 1976   2.8125     6.7834      -22.6995     28.3245  
  1985 1977  -2.1400     3.6248      -15.7728     11.4929  
  1985 1978   5.7781     5.6068      -15.3088     26.8651  
  1985 1979  -3.8368    10.6480      -43.8837     36.2102  
  1985 1980   1.5265     7.0875      -25.1295     28.1825  
  1985 1981  -2.8105     5.6947      -24.2281     18.6071  
  1985 1982  13.2242    10.2165      -25.1996     51.6479  
  1985 1983  -5.5714    10.1458      -43.7295     32.5867  
  1985 1984  -5.5493     3.0237      -16.9212      5.8225  
  1985 1985  11.4728     6.8301      -14.2148     37.1605  
  1985 1986  10.1715     3.4372       -2.7558     23.0989  
  1985 1987  17.5291     4.9075       -0.9279     35.9861  
  1985 1988  -9.6423     3.9206      -24.3875      5.1030  
  1985 1989  19.8229     5.3527       -0.3085     39.9542  
  1985 1990  26.2350     0.9371       22.7106     29.7594 *
  1985 1991   6.2209     3.7879       -8.0253     20.4671  
  1985 1992  18.3602     6.2606       -5.1856     41.9059  
  1985 1993  23.0343     2.8095       12.4679     33.6008 *
  1985 1994  15.2612     6.2622       -8.2907     38.8131  
  1985 1995  15.4633     4.4738       -1.3625     32.2892  
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Outcome Regression</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdid</span>(atts_nt)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p>[10 puntos] Reporte los resultados agregados obtenidos a partir del estimador Callaway &amp; Sant’Anna (2021), usando una agregación dinámica que muestre los efectos promedio para cada periodo antes y después del tratamiento. Grafique e interprete los resultados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>agg.es <span class="ot">&lt;-</span> <span class="fu">aggte</span>(atts_nt,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"dynamic"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(agg.es)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aggte(MP = atts_nt, type = "dynamic")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 


Overall summary of ATT's based on event-study/dynamic aggregation:  
      ATT    Std. Error     [ 95%  Conf. Int.]  
 -11.4964        3.7288   -18.8047     -4.1881 *


Dynamic Effects:
 Event time Estimate Std. Error [95% Simult.  Conf. Band]  
        -19  29.3180    10.1469        1.3095     57.3266 *
        -18  -7.9539     1.8476      -13.0538     -2.8540 *
        -17   2.1023     5.9725      -14.3837     18.5883  
        -16   4.5214     5.6877      -11.1785     20.2213  
        -15   8.1583     5.9371       -8.2299     24.5465  
        -14   0.1417     4.8451      -13.2322     13.5156  
        -13   1.6657     7.2660      -18.3906     21.7220  
        -12 -11.0144    14.9396      -52.2524     30.2235  
        -11  -9.0818     7.5219      -29.8445     11.6808  
        -10   8.0943     6.4728       -9.7727     25.9614  
         -9  -7.0756     5.2780      -21.6446      7.4934  
         -8   4.2068     4.1602       -7.2766     15.6902  
         -7  -2.2507     4.5544      -14.8223     10.3209  
         -6   5.6460     3.7781       -4.7828     16.0748  
         -5  -3.4392     3.4505      -12.9635      6.0851  
         -4   5.1665     2.6344       -2.1052     12.4383  
         -3  -0.3596     2.1774       -6.3699      5.6508  
         -2   1.1409     2.5639       -5.9363      8.2182  
         -1   1.9481     3.1449       -6.7330     10.6291  
          0  -0.8065     2.8923       -8.7902      7.1773  
          1  -2.7726     3.0902      -11.3025      5.7573  
          2  -4.2845     4.3780      -16.3691      7.8001  
          3  -3.9743     2.8756      -11.9117      3.9631  
          4  -4.5620     3.5778      -14.4376      5.3137  
          5  -7.4465     3.1521      -16.1472      1.2542  
          6  -6.2541     3.9075      -17.0399      4.5317  
          7 -10.6094     3.5133      -20.3071     -0.9117 *
          8  -9.9746     3.5535      -19.7834     -0.1658 *
          9 -10.1110     3.7334      -20.4164      0.1944  
         10 -11.0023     3.9502      -21.9060     -0.0987 *
         11 -13.3679     3.8009      -23.8595     -2.8763 *
         12  -8.7828     4.8173      -22.0800      4.5144  
         13 -12.1880     4.0827      -23.4575     -0.9185 *
         14 -11.2760     4.5907      -23.9478      1.3958  
         15 -14.8487     5.0057      -28.6658     -1.0315 *
         16 -11.7709     5.1512      -25.9897      2.4479  
         17 -14.3232     4.7228      -27.3595     -1.2869 *
         18 -17.1010     4.6834      -30.0288     -4.1733 *
         19 -17.6118     4.2504      -29.3443     -5.8793 *
         20 -14.8085     5.0632      -28.7847     -0.8324 *
         21 -16.5371     4.7367      -29.6117     -3.4624 *
         22 -15.2723     4.6988      -28.2424     -2.3022 *
         23 -17.6177     7.3821      -37.9947      2.7593  
         24 -19.0284     8.8203      -43.3752      5.3184  
         25 -27.2842    19.0460      -79.8569     25.2886  
         26  -6.7870    16.2988      -51.7766     38.2026  
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Outcome Regression</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdid</span>(agg.es)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea-4-respuestas_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Se obtiene una reducción en la tasa de suicidios que es estadísticamente significativa a partir de 5 años después de la introducción de la legislación.</em></p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>